version: '2'

services:
  apache-php:
    image: apache
    container_name: apache-php 
    restart: always
    environment:
        VERSION: 1.0.4
    network_mode: host
    volumes:
        - /data/apache/sites-enabled:/etc/apache2/sites-enabled
        - ./ports.conf:/etc/apache2/ports.conf
        - ./apache2.conf:/etc/apache2/apache2.conf
        - ./php.ini:/etc/php5/apache2/php.ini
        - /data/code/jinyu/Site:/var/www/html
        - /data/code:/data/code
        - /data/log:/data/log
  apache-php2:
    image: apache
    container_name: apache-php2
    restart: always
    environment:
        VERSION: 1.0.1
    network_mode: host
    volumes:
        # - /var/run/docker-mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
        - /data/apache/sites-enabled:/etc/apache2/sites-enabled
        - ./jinyu-admin2/ports.conf:/etc/apache2/ports.conf
        - ./apache2.conf:/etc/apache2/apache2.conf
        - ./php.ini:/etc/php5/apache2/php.ini
        - /data/code/art/laravel/public:/var/www/html
        - /data/code:/data/code
        - /data/code/python/thrift/gen-php/Services:/data/code/art/laravel/ThriftRpc/Services
        - /data/log:/data/log
